### ISSUE TITLE
Docs: custom resource name

### ISSUE THREAD

**Issue by PrettySolution** [cdklabs/cdk-ecs-service-extensions#296]
Hi,

I have a requirement to set custom Service and TaskDefinition names.
Is that posible?

thanks!

**Comment by bvtujo** [comment]
Hey there! Thanks for asking. We don't necessarily recommend doing this, as changing the service name can trigger a [replacement of the CFN resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-servicename). That's why we don't have the Name property exposed in the `ServiceBuild` interface. If you really need to change it, you could do so by modifying the underlying service after it's created.  

You can do both of those things with a custom extension. 

You could use the `modifyTaskDefinitionProps` and `useService` functions in the `ServiceExtension` interface like so:

```typescript
public class NameExtension extends ServiceExtension {
  
  constructor(private readonly taskDefFamily: string, private readonly serviceName: string) {
    super('name-extension');
  }

  public modifyTaskDefinitionProps(props: ecs.TaskDefinitionProps): ecs.TaskDefinitionProps {
    return {
      ...props,
      family: this.taskDefFamily,
    } as ecs.TaskDefinitionProps;
  }

  public useService(service: ecs.Ec2Service | ecs.FargateService) {
    service.defaultChild.serviceName = this.serviceName;
  }
}
```

**Comment by bvtujo** [comment]
Does that help? Feel free to reopen if this doesn't work for you!
